### PR TITLE
remove old npm slave and add new upstream one

### LINKED ISSUE #158: Remove NPM Slave In Favor of New Upstream Slave
https://github.com/openshift/jenkins/tree/master/agent-nodejs-8

### PR DESCRIPTION
**Pull request by sherl0cks**
resolves #158

### CODE REVIEW

**Comment by sherl0cks** [comment]
@springdo could you review this change? There is info here relevant to your work right now. 
@rdebeasi @mdanter @mcanoy @pcarney8 @logandonley FYI

**Comment by springdo** [comment]
Cool man, I'll take a look in more detail when I get in to the office!

**Comment by springdo** [comment]
@sherl0cks  - if you are going to remove the Chrome install from the container; can we create a new one that has it please? Im guessing you'll probs just want this created in CoP land?

**Comment by sherl0cks** [comment]
@springdo hmmm - didn't really think through that. good catch. I think we may want to push it all the way upstream to openshift, not the CoP. I'll open an issue in openshift land to get the discussion started, though they are likely not going to want to do it. if we go CoP route, the current issue is that the new openshift jenkins slaves builds aren't pushed to the red hat contianer registry yet, so you need to build the base image first in order to extend it.

**Comment by sherl0cks** [comment]
@springdo see https://github.com/openshift/jenkins/issues/570. for now, let's close this out and then based on the outcome of the openshift ticket, we can create a new slave in CoP land if it make sense.

**Comment by springdo** [comment]
yeah man; that's cool. If we don't hear much from the guys in OCP land soon I'll shove it into the CoP. Will merge your stuff for now

**Pull request merged**
