### PR TITLE
support more flexible regexp replace and better user facing playbooks

### LINKED ISSUE #123: make-demo-unique appends instead of replacing
The `make-demo-unique` appends the project name instead of replacing it, causing the project name to become longer each time the command is run.

For example, here's the command that I'm currently running:
```
ansible-playbook ci-playbook.yaml -i inventory/ -e demo_projectname=ryan-test -e scm_ref=HEAD
```

This results in a project called `labs-ci-cd-ryan-test`. I'd expect the project to be called `ryan-test`.

I encountered an unrelated error related to postgresql. I ran the same playbook again, causing my project name to become `ryan-test-ryan-test`. In `params/jenkins/deploy`:
```
NAMESPACE=labs-ci-cd-ryan-test-ryan-test
```
I'd expect to see this:
```
NAMESPACE=ryan-test
```

Running the playbook a few times will cause the project name to exceed the 63-character limit, causing further runs to fail. A short-term workaround is to reset the playbook to its initial state by running `git checkout params`. (You will _lose any config changes that you have made_.)

### PR DESCRIPTION
**Pull request by sherl0cks**
resolves #123 #124 

@oybed @esauer @sabre1041 : this approach provides a generic way to pass a var to regexp/replace contents of applier params files

### CODE REVIEW

**Comment by rdebeasi** [comment]
I'd like to propose a few changes to clarify the readme text. I'll create a PR for Justin's branch with these changes.

**Comment by sherl0cks** [comment]
@rdebasi would it help to just have 1 playbook. Turns out dynamically including the role was easier than I realized...

http://docs.ansible.com/ansible/latest/include_role_module.html

**Comment by rdebeasi** [comment]
Sure, that would help!

I'd still like to update the instructions to say something like what you said in chat:
>  if you want `labs-ci-cd`, `labs-dev`, `labs-demo` run the default
> if you `labs-ci-cd-uniqueness` `labs-dev-uniquenes` `labs-demo-uniqueness` run this other thing with a param 

In particular, I'd like to make it clear that the former option is the "default" and should work for most ci-cd users. The latter option is really only useful if for contributors to ci-cd. That way, new users don't have to puzzle out which option is right for them.

**Comment by oybed** [comment]
@sherl0cks just beware that the `include_role` is what's having a problem with dynamic includes pre Ansible 2.5 and what the `openshift-applier` has been waiting for a fix to be able to do pre/post steps. If we can standardize on using the `openshift-applier` container for run-time use (which I believe we should anyway), I think we'll be fine, but otherwise you may be bit by the same issue till 2.5 is out.

**Comment by oybed** [comment]
@sabre1041 @etsauer FYI just a bit more background info - this is based on the [make-demo-unique](https://github.com/rht-labs/labs-demo/tree/master/roles/make-demo-unique) role that was introduced for the Labs demo env. @sherl0cks and I had a discussion a few weeks back re: the use of this role and making it more broadly usable. We agreed that making the changes that's part of this PR will allow for greater flexibility. Once this has been merged, it will be moved to `casl-ansible` for consumption by others as this is something that's typically `openshift-applier` related.

**Comment by sherl0cks** [comment]
@oybed ahh that's it. I knew something was off here. We'll keep the two playbook for now

**Pull request merged**
