### PR TITLE
Update to get pod label and then use that for the route (more dynamic fix the `BUILD_URL` issue)

### PR DESCRIPTION
**Pull request by pcarney8**

### CODE REVIEW

**Comment by springdo** [comment]
@sherl0cks, @pcarney8  - I've run the CI Job for you. I'll mergé if it's not borked!

**Comment by springdo** [comment]
Seems to be some issue with the `zap` slave. Let me re-run it incase it was just being flakey....

```
08:45:54 [ZAP] [labs-ci-cd-pr-197-test-slaves-pipeline] Running shell script
08:45:54 [ZAP] + /zap/zap-baseline.py -r index.html -t https://google.com
08:45:55 [ZAP] _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
08:46:03 [ZAP] Jul 31, 2018 8:46:02 AM java.util.prefs.FileSystemPreferences$1 run
08:46:03 [ZAP] INFO: Created user preferences directory.
08:48:10 [ZAP] 2018-07-31 08:47:55,624 I/O error(5): Failed to connect to ZAP after 120 seconds
08:48:10 [ZAP] ERROR Failed to connect to ZAP after 120 seconds
```

**Comment by pcarney8** [comment]
@springdo looks like [Build #121](https://jenkins-labs-ci-cd.apps.s9.core.rht-labs.com/job/labs-ci-cd/job/labs-ci-cd-ci-for-labs-ci-cd-pipeline-pipeline-feature-change-for-new-ci-cd-pipeline/) passed. Mergé?

**Comment by sherl0cks** [comment]
@springdo - I like the added checks in the jenkins job! just seeing that.

@pcarney8 lgtm

**Comment by sherl0cks** [comment]
@pcarney8 is there an issue this resolves that needs closing?

**Comment by pcarney8** [comment]
@sherl0cks no, :grimacing: i believe i forgot to open an issue. i know PR #183 addressed this issue first, this is really just an enhancement to that fix

**Comment by sherl0cks** [comment]
no worries, just trying to keep the backlog clean

**Pull request merged**
