### PR TITLE
Update GitLab, add SSL support and move to YAML

### PR DESCRIPTION
**Pull request by makentenza**
Modify the existing GitLab stack template, to update GitLab CE version to 10.2.3-ce.0, add SSL support (cert generation and configuration is already automated on the template) and move to YAML from JSON (this is for the same standardization we are following on the CoP)

### CODE REVIEW

**Comment by makentenza** [comment]
@sherl0cks do you think we could merge this? once is done will work on moving JSON files to YAML on this repo. I think we agreed to do so in December, true?

**Comment by sherl0cks** [comment]
Mak the issue here is two fold. 1) is lack of CI. The meta issue of CI'ing our CI has been a challenge for a long time. Manually testing and reviewing this stuff is slow and time consuming 2) Other work is taking priority. I've raised this as a challenge to Mike, he is aware, but until we have a model that allows folks to be dedicated to this project, its going to persist.

As to moving to yaml, that's fine by me. But again, we need CI to prevent regressions (which have impacted residency recently) before moving everything

**Comment by sherl0cks** [comment]
@makentenza I used this PR for testing a lot of the functionality of https://github.com/rht-labs/labs-ci-cd/pull/87, which is now merged. 

To help me merge this PR, is it possible to add gitlab to the inventory and then update the Jenkinsfile with the relevant info? Please ping me with queries.

**Comment by makentenza** [comment]
@sherl0cks sure, great to see the CI stuff. Will add gitlab to the inventory as well.

**Comment by springdo** [comment]
@makentenza & @sherl0cks  - given other work is taking priority for you guys and we're about to become more free (for like; a week!); perhaps Mak and I can pair on getting this in and I can learn some more about how the team has been building out this repo?

**Comment by makentenza** [comment]
Yeah, we can definitely work on this next week @springdo

**Comment by sherl0cks** [comment]
sounds good to me. there is a healthy backlog of issues. I'm pretty confident in the CI job now. we maybe want to discuss that over bluejeans so you feel comfortable running it.

**Comment by makentenza** [comment]
@sherl0cks where is the Jenkins we are using to trigger the CI job?

**Comment by sherl0cks** [comment]
It's in S7 more info to come in chat

**Comment by sherl0cks** [comment]
@makentenza  @springdo any luck getting the inventory updated? do you need any other support from me?

**Comment by makentenza** [comment]
@sherl0cks I tried to add this yesterday, but if we need perform tests with GitLab we will need to put LDAP sensible info on the repo and that would be a bad idea. Could we use Jenkins credentials on the job for this?

**Comment by makentenza** [comment]
@sherl0cks as discussed moving this to the CoP's containers-quickstarts repo[1]

[1] https://github.com/redhat-cop/containers-quickstarts/pull/67

**Pull request closed without merging**
