### PR TITLE
A scheduled job that will sync two git repos with SSH

### PR DESCRIPTION
**Pull request by pcarney8**
This will allow for **all** branches to be pushed to a backup git server.

### CODE REVIEW

**Comment by sherl0cks** [comment]
@day4skiing @oybed @makentenza can someone from the SRE team please review this

**Comment by oybed** [comment]
@sherl0cks @pcarney8 yes, and as I worked with Patrick on this one and provided some of the stuff, I think I'm fine with it.  However, I was wanting to see if we could rather submit this to the [openshift-management [1]](https://github.com/redhat-cop/openshift-management/tree/master/jobs) repo with some of the other "utility" jobs - or do you guys think it's a better fit for this repo?

Also; @makentenza just submitted some updates to the existing jobs in that repo, so you may want to look to update this job with the same enhancements.
https://github.com/redhat-cop/openshift-management/pull/13
 

[1] : `https://github.com/redhat-cop/openshift-management/tree/master/jobs`

**Comment by sherl0cks** [comment]
@oybed I'm cool with whatever ya'll wanna do.

**Comment by pcarney8** [comment]
@oybed so change it from `ScheduledJob` to `CronJob` and move this into [openshift-management](https://github.com/redhat-cop/openshift-management/tree/master/jobs)? I can do that if that's what you want, and then I'll close this PR

**Comment by oybed** [comment]
@pcarney8 if you all are ok with that plan, I think that sounds good

**Comment by sherl0cks** [comment]
@pcarney8 can we close this now that https://github.com/redhat-cop/openshift-management/pull/14 is open?

**Pull request closed without merging**
