### PR TITLE
Applier v2 with merge conflicts resolved

### PR DESCRIPTION
**Pull request by sherl0cks**
replaces #203 as @oybed is out and we need this ball to keep rolling. @oybed should still get contrib credit.

### CODE REVIEW

**Comment by sherl0cks** [comment]
This issue is hitting the inception problem - changes are being made to the Jenkinsfile but that is the one file we can not test in the CI itself right now. The way around this is to copy / paste the Jenkinsfile into the BuildConfig as described in #204. Once I do that, here is the info I see:

```
[labs-ci-cd] Running shell script
+ ansible-playbook ci-playbook.yml -vvv -i inventory/ -e 'target=bootstrap project_name_postfix=-pr-212 scm_ref=pr-212'
ansible-playbook 2.5.8
  config file = /tmp/workspace/labs-ci-cd/labs-ci-cd-ci-for-labs-ci-cd-pipeline/labs-ci-cd/ansible.cfg
  configured module search path = [u'/home/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /tmp/workspace/labs-ci-cd/labs-ci-cd-ci-for-labs-ci-cd-pipeline/labs-ci-cd/ansible.cfg as config file
Parsed /tmp/workspace/labs-ci-cd/labs-ci-cd-ci-for-labs-ci-cd-pipeline/labs-ci-cd/inventory/hosts inventory source with ini plugin
ERROR! Unexpected Exception, this is probably a bug: No module named requests
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 81, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 54, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 106, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 111, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 256, in load_data
    self._attributes[target_name] = method(name, ds[name])
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 192, in _load_roles
    roles.append(Role.load(ri, play=self))
  File "/usr/lib/python2.7/site-packages/ansible/playbook/role/__init__.py", line 157, in load
    r._load_role_data(role_include, parent_role=parent_role)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/role/__init__.py", line 211, in _load_role_data
    self._task_blocks = load_list_of_blocks(task_data, play=self._play, role=self, loader=self._loader, variable_manager=self._variable_manager)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/helpers.py", line 80, in load_list_of_blocks
    loader=loader,
  File "/usr/lib/python2.7/site-packages/ansible/playbook/block.py", line 93, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 256, in load_data
    self._attributes[target_name] = method(name, ds[name])
  File "/usr/lib/python2.7/site-packages/ansible/playbook/block.py", line 129, in _load_block
    use_handlers=self._use_handlers,
  File "/usr/lib/python2.7/site-packages/ansible/playbook/helpers.py", line 139, in load_list_of_tasks
    all_vars = variable_manager.get_vars(play=play, task=t)
  File "/usr/lib/python2.7/site-packages/ansible/vars/manager.py", line 425, in get_vars
    all_vars['ansible_delegated_vars'] = self._get_delegated_vars(play, task, all_vars)
  File "/usr/lib/python2.7/site-packages/ansible/vars/manager.py", line 494, in _get_delegated_vars
    loader=self._loader, fail_on_undefined=True, convert_bare=False)
  File "/usr/lib/python2.7/site-packages/ansible/utils/listify.py", line 36, in listify_lookup_plugin_terms
    terms = templar.template(terms, fail_on_undefined=fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 513, in template
    ) for v in variable]
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 481, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 686, in do_template
    myenv.filters.update(self._get_filters(myenv.filters))
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 302, in _get_filters
    plugins = [x for x in self._filter_loader.all()]
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 435, in all
    module = self._load_module_source(name, path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 345, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/tmp/workspace/labs-ci-cd/labs-ci-cd-ci-for-labs-ci-cd-pipeline/labs-ci-cd/roles/openshift-applier/roles/openshift-applier/filter_plugins/applier-filters.py", line 2, in <module>
    import requests
ImportError: No module named requests
```

**Comment by sherl0cks** [comment]
Looks like `pip` is not available in the Jenkins ansible slave. I'm stuck.

**Comment by oybed** [comment]
@sherl0cks The `request` dependency is being taken care of with PR https://github.com/redhat-cop/openshift-applier/pull/50. As soon as that PR merges, we'll cut a `v2.0.1` of the applier and Labs CI/CD can be moved to that release.

**Comment by sherl0cks** [comment]
@oybed ACK - I'll leave this open until that time, may need to back out a change or two. Thank you

**Comment by oybed** [comment]
@sherl0cks `v2.0.2` is out: https://github.com/redhat-cop/openshift-applier/releases/tag/v2.0.2

**Comment by oybed** [comment]
Closing out as @203 is now back on track.

**Pull request closed without merging**
