### PR TITLE
update Jenkins plugins

### LINKED ISSUE #82: remove blueocean and transitives for 3.7 onwards
shipped in ocp base image

### PR DESCRIPTION
**Pull request by sherl0cks**
resolves #82

### CODE REVIEW

**Comment by sherl0cks** [comment]
Appears we have issues with https://github.com/openshift/jenkins/pull/490 and https://github.com/openshift/jenkins/issues/495. This needs more investigation

**Comment by sherl0cks** [comment]
looks like downgrading `openshift-sync:0.1.32` works

**Comment by oybed** [comment]
Note that version `0.1.32` of the sync plugin has the fix for "immediate build start" in Jenkins that we have received a lot of feedback on in the demo env. Hence, staying on `0.1.32` and newer is good. 

https://bugzilla.redhat.com/show_bug.cgi?id=1537317

**Comment by sherl0cks** [comment]
good to know. `0.1.32` is the latest stable version as far as I'm concerned

**Pull request merged**
