### PR TITLE
Delete projects before creating to ensure clean slate

### LINKED ISSUE #107: Add Mechanism to Delete CI projects in the future

### LINKED ISSUE #108: Have CI job delete project if it already exists, and then recreate fresh

### PR DESCRIPTION
**Pull request by Tompage1994**
closes #108 

Also probably closes #107 as well?

### CODE REVIEW

**Comment by springdo** [comment]
@makentenza  - is there a nice way in OCP land to verify all content has been deleted for a given namespace?

**Comment by makentenza** [comment]
Not really @springdo. Apart of "oc get all" or doing custom API calls, there are still lot of content on global objects related to one particular namespace you can directly query. Relationship for RBAC mechanism, or relations between namespace's SA and global SCCs....

AFAIR, the only way to get the info was from ETCD as normally all related namespace objects are on the same tree, but using this approach for this process is to complicate things too much I guess.

One solution we normally use for other repos is to get a ready process to delete all the objects created from a given automation, as you know perfectly which objects have been created. If you have that info stored somewhere as an inventory from the deployment, then remove these objects is much more easy.

**Comment by makentenza** [comment]
@springdo check this "solution", it would help

https://access.redhat.com/solutions/3340581

**Comment by Tompage1994** [comment]
@makentenza I think the 'dump-projects.sh' solution may have been a bit overkill for this. @ckyriakidou thought waiting for 'oc get <project>' to fail may be a better solution.

**Comment by springdo** [comment]
@Tompage1994  - there has been a request from the team to delete the things created by CI for the labs CI/CD _if_ the build has been succesful.... So I would suggest you replay your `command` string at the end of the parallel when the job has finished executing.

**Comment by makentenza** [comment]
@Tompage1994 As I said, `oc get all` will not cover any object that has been modified out from the scope of the namespace you are working on. The `dump-projects.sh` is an example to get all the info around one particular project, I'm not suggesting to use that here, as it takes a lot of time to get all the info, it was just an example.

My suggestion around logging all the objects created by this repository to use the info later is probably the better approach and the easiest to implement.

**Comment by makentenza** [comment]
LGTM now, merging

**Comment by Tompage1994** [comment]
@springdo I have now run `command` at the end as well to cover what you mentioned.

@makentenza myself and Donal discussed this earlier and decided it possibly wasn't a problem if images etc. still exist due to the fact that if the image wont have changed then it doesn't matter if it pulls it... if it should have changed then it will build from scratch anyway. Not sure if there would be any unintended side-effects though?

**Comment by Tompage1994** [comment]
Closing due to #181

**Pull request closed without merging**
