### PR TITLE
Added NIST CVE feeds as proxy repo to Nexus

### LINKED ISSUE #194: Add Proxy repo to Nexus for NIST CVE data to be used with OWASP Dependency Check
Configure post step for Nexus to add a Raw Proxy for the NIST CVE database files to be used with OWASP Dependency Check.

More details available at: https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html

The URLs to be mirrored would be:

Type|Property|Comment|URL
-- | -- | -- | --
cve | url12Modified | URL for the modified CVE 1.2. | https://nvd.nist.gov/feeds/xml/cve/1.2/nvdcve-modified.xml.gz
cve | url20Modified | URL for the modified CVE 2.0. | https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-Modified.xml.gz
cve | url12Base | Base URL for each year’s CVE 1.2, the %d will be replaced with the year. | https://nvd.nist.gov/feeds/xml/cve/1.2/nvdcve-%d.xml.gz
cve | url20Base | Base URL for each year’s CVE 2.0, the %d will be replaced with the year. | https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-%d.xml.gz

### PR DESCRIPTION
**Pull request by InfoSec812**
Resolves #194

### CODE REVIEW

**Comment by InfoSec812** [comment]
The CI job will not succeed because the galaxy_requirements points to the wrong branch.

**Comment by sherl0cks** [comment]
@InfoSec812 there is some fancy reg exp replace stuff that modifies the source to properly test PRs, including `galaxy_requirements.yml`. You can find that [here](https://github.com/redhat-cop/openshift-applier/blob/master/roles/make-applier-projects-unique/tasks/update-galaxy-requirements.yml).

Logs from the CI job below as proof:
```
TASK [openshift-applier/roles/make-applier-projects-unique : Update galaxy requirements file] ***
skipping: [projects-and-policies] => (item={u'content': [{u'template_action': u'create', u'params': u'/tmp/workspace/labs-ci-cd/labs-ci-cd-ci-for-labs-ci-cd-pipeline/labs-ci-cd/params/projectrequests/ci-cd', u'name': u'ci-cd', u'template': u'https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml', u'tags': [u'projects']}, {u'template_action': u'create', u'params': u'/tmp/workspace/labs-ci-cd/labs-ci-cd-ci-for-labs-ci-cd-pipeline/labs-ci-cd/params/projectrequests/dev', u'name': u'dev', u'template': u'https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml', u'tags': [u'projects']}, {u'template_action': u'create', u'params': u'/tmp/workspace/labs-ci-cd/labs-ci-cd-ci-for-labs-ci-cd-pipeline/labs-ci-cd/params/projectrequests/test', u'name': u'demo', u'template': u'https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml', u'tags': [u'projects']}], u'object': u'projectrequest'}) 
skipping: [projects-and-policies] => (item={u'content': [{u'namespace': u'labs-ci-cd', u'params': u'/tmp/workspace/labs-ci-cd/labs-ci-cd-ci-for-labs-ci-cd-pipeline/labs-ci-cd/params/rolebinding-group/all', u'name': u'ci-cd-acl', u'template': u'/tmp/workspace/labs-ci-cd/labs-ci-cd-ci-for-labs-ci-cd-pipeline/labs-ci-cd/openshift-templates/rolebinding-group/template.yml', u'tags': [u'rolebinding-group']}, {u'namespace': u'labs-dev', u'params': u'/tmp/workspace/labs-ci-cd/labs-ci-cd-ci-for-labs-ci-cd-pipeline/labs-ci-cd/params/rolebinding-group/all', u'name': u'labs-dev-acl', u'template': u'/tmp/workspace/labs-ci-cd/labs-ci-cd-ci-for-labs-ci-cd-pipeline/labs-ci-cd/openshift-templates/rolebinding-group/template.yml', u'tags': [u'rolebinding-group']}, {u'namespace': u'labs-test', u'params': u'/tmp/workspace/labs-ci-cd/labs-ci-cd-ci-for-labs-ci-cd-pipeline/labs-ci-cd/params/rolebinding-group/all', u'name': u'labs-dev-acl', u'template': u'/tmp/workspace/labs-ci-cd/labs-ci-cd-ci-for-labs-ci-cd-pipeline/labs-ci-cd/openshift-templates/rolebinding-group/template.yml', u'tags': [u'rolebinding-group']}], u'object': u'group-role-binding'}) 
```

**Comment by sherl0cks** [comment]
@InfoSec812 I see that your repo is being created in the PR build. It's been awhile since I've touched the guts of that PR testing logic, but despite some confusing logging, it seems to be working as expected.

screenshot from 2018-09-20 13-59-06

**Comment by sherl0cks** [comment]
@InfoSec812 thanks Deven!

**Pull request merged**
