### PR TITLE
Gogs custom template with LDAP Integration example

### PR DESCRIPTION
**Pull request by makentenza**
OpenShift template for Gogs with SSL support. LDAP integration is not yet part of the template parameters as can't be automated yet. There is an open issue right now, so this will be added as soon is closed.

### CODE REVIEW

**Comment by InfoSec812** [comment]
@makentenza Why wouldn't we just integrate with OpenShift OAuth instead of worrying about LDAP? Then, we benefit from whatever integration OpenShift already has and we don't have to modify the implementation for different environments based on their Auth subsystem.

**Comment by makentenza** [comment]
@InfoSec812 The idea was to integrate with OAuth as well, but even this was supported at some point in Gogs, is not anymore apparently. There are some issues where people are requesting it, so we could enable that once is implemented.

Same for LDAP, there is already an issue where adding LDAP configuration to app.ini has been requested. That will allow us to automate the integration within the template, which is not possible right now.

**Comment by InfoSec812** [comment]
The simple solution I am aware of is to use an OAuth Reverse Proxy like [this](https://github.com/openshift/oauth-proxy). We could add this to the template so that OAuth is integrated at the start.

**Comment by makentenza** [comment]
@InfoSec812 even if we can run the reverse proxy as a sidecar container I can't see how we can integrate that into Gogs, so any example will be welcomed.

**Comment by InfoSec812** [comment]
I'm working on it here... I should have a PR for you to test shortly...

**Pull request merged**
